### ISSUE TITLE
【Bug】リポスト・ふぁぼのクロスタイミングでのリアクション表記が実態とずれる

### ISSUE THREAD

**Issue by ShinoharaTa** [akiomik/seiun#7]
ふぁぼ→リポスト→ふぁぼレスポンス→リポストレスポンス

この状態の時、ふぁぼのアイコンがアクティブにならず、リポストのみ完了したことになってしまいます。

処理がキャンセルされてしまう・・・？
実際の挙動を見ていると、ふぁぼ・リポストともに完了していることを確認しました

**Comment by akiomik** [comment]
ご報告ありがとうございます！レースコンディションが発生してるので、常に最新の値を使うように修正する必要がありそうです。

This is a race condition issue. To avoid this, we must use `feedPost` from `feedViewPosts` instead of arguments.

https://github.com/akiomik/seiun/blob/4ace37b4d343604c30d2a88c396484514792dd47/app/src/main/java/io/github/akiomik/seiun/viewmodel/TimelineViewModel.kt#L114-L120

https://github.com/akiomik/seiun/blob/4ace37b4d343604c30d2a88c396484514792dd47/app/src/main/java/io/github/akiomik/seiun/viewmodel/TimelineViewModel.kt#L166-L175

**Comment by akiomik** [comment]
This issue is closed since https://github.com/akiomik/seiun/commit/9f41e3c65fff2308ab21e57d5d3e9b995ef4669f fixed it.

問題が継続or再発したらreopenしてください 🙏
